### ISSUE TITLE
please clarify meaning and semantics of PacketTypeMPEG2TSSequenceStart

### ISSUE THREAD

**Issue by zenomt** [veovera/enhanced-rtmp#12]
`PacketTypeMPEG2TSSequenceStart` is referenced in the pseudocode for AV1. please clarify whether:
1. this packet type has a meaning for any other codecs
2. if this packet type can be used in combination with `PacketTypeSequenceStart` or if they are mutually exclusive. if they can be used in combination, which one SHOULD/MUST come first?

how and for what is `PacketTypeMPEG2TSSequenceStart` expected to be used?

**Comment by zenomt** [comment]
with a name like `PacketTypeMPEG2TSSequenceStart`, i'd assume this marks the beginning of a video sequence just like `PacketTypeSequenceStart`, which means they are mutually exclusive.

knowing whether there will be just one sequence init message or potentially two affects implementations that need to remember the init message(s) and send it/them to new subscribers.

**Comment by pkviet** [comment]
Hi @zenomt 
1. it's for AV1 exclusively.
2.  `PacketTypeSequenceStart`  and `PacketTypeMPEG2TSSequenceStart` are exclusive.

`PacketTypeSequenceStart` should be : AV1CodecConfigurationRecord from [https://aomediacodec.github.io/av1-isobmff/#av1codecconfigurationbox-syntax](https://aomediacodec.github.io/av1-isobmff/#av1codecconfigurationbox-syntax)
`PacketTypeMPEG2TSSequenceStart` should be : AV1_video_descriptor()  from https://aomediacodec.github.io/av1-mpeg2-ts/#syntax-0 

The two structs differ a little bit in that the latter carries hdr information + descriptor tag and length. The former has also at the end a configOBUS field. 

That's a request we made at obsproject to the spec authors since we expect to support the av1 in mpegts spec and the hdr info is useful.

**Comment by zenomt** [comment]
hi @pkviet . thanks for the clarification. this simplifies my implementation. :)

i see (now) in the spec that there are hyperlinks to those two AV1 docs in the `IF FourCC == AV1` section. @veovera i'd suggest as an editorial change also putting those URIs or human-interpretable references to the relevant doc sections as text in `//` comments in that section, for folks who might come across the spec in a printed or transformed form that doesn't preserve the hyperlinks, or in a viewer that doesn't enable following hyperlinks. likewise for `VPCodecConfigurationRecord` in the VP9 section.

**Comment by veovera** [comment]
thx @pkviet and @zenomt for helping to clarify this. spec will be updated with the clarification in the next update. Closing the issue
